server:
  port: 8776
spring:
  application:
    name: sap-api
  zipkin:
    base-url: http://116.62.6.120:8881
eureka:
  instance:
    hostname: 47.114.188.60
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://116.62.6.120:8060/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
security:
  oauth2:
    client:
      client-id: miniWehcat
      client-secret: password
      user-authorization-uri: http://116.62.6.120/auth/oauth/authorize
      access-token-uri: http://116.62.6.120/auth/oauth/token #获取Token
      refresh-token-uri: http://116.62.6.120/auth/oauth/token
    resource:
      jwt:
        key-uri: http://116.62.6.120/auth/oauth/token_key
