server:
  port: 8851
spring:
  cloud:
    inetutils:
      ignored-interfaces[0]: eth0
      ignored-interfaces[1]: eth2
  application:
    name: dingtalk-web
  boot:
    admin:
      client:
        url: http://106.12.184.126:8880
  zipkin:
    base-url: http://106.12.184.126:8881
eureka:
  instance:
    hostname: 49.234.225.92
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://106.12.184.126:8060/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000