server:
  port: 8851
spring:
  application:
    name: dingtalk-web
  zipkin:
    base-url: http://106.12.184.126:8881
eureka:
  instance:
    hostname: 49.234.225.92
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://106.12.184.126:8060/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000
lanson:
  plm:
    objectHref: http://10.20.0.7:8080/enovia/common/emxTree.jsp?objectId=
  ding:
    app[0]:
      AgentId: 276867937
      AppKey: dingjqucgxash2keqrql
      AppSecret: a73spFkomTg4xZODa_53XEG3Kuj7TbDN2pTtVHPblxRSrc61DE7pYsQmlf7titoU
    app[1]:
      AgentId: 278347056
      AppKey: dinglxzrz5lzraevbfet
      AppSecret: 9HfrVS9_RoqXDzVwlXxDQnV4VuzPggddQU-GksrinHXJEbFL_APz0jUy3qu2oheL
    robot[0]:
      accessToken: 322c5acc15c4f077de331affb155a06ff1c84e30a0184bd85a5c3cb731fa0f5b