server:
  port: 8851
spring:
  application:
    name: dingtalk-web
  boot:
    admin:
      client:
        url: http://localhost:8880
  zipkin:
    base-url: http://localhost:8881
eureka:
  instance:
    hostname: 10.20.2.101
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
