server:
  port: 8870
spring:
  application:
    name: redis-service
  zipkin:
    base-url: http://116.62.6.120:8881
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 2000
eureka:
  instance:
    hostname: 116.62.6.120
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://116.62.6.120:8060/eureka/
