server:
  port: 8858
spring:
  application:
    name: sap-service
  boot:
    admin:
      client:
        url: http://116.62.6.120:8881
  servlet:
    multipart:
      max-file-size: 40MB #上传文件大小限制
      max-request-size: 40MB
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:static/
eureka:
  instance:
    hostname: 122.225.237.18
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://116.62.6.120:8060/eureka/

