server:
  port: 8858
spring:
  application:
    name: sap-service
  zipkin:
    base-url: http://106.12.184.126:8881
  datasource:
    druid:
      url: jdbc:mysql://49.234.225.92:3306/wechat_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: Wang#1990
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
  servlet:
    multipart:
      max-file-size: 40MB #上传文件大小限制
      max-request-size: 40MB
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/filedb # MongoDB数据库连接配置
mybatis:
  type-aliases-package: om.lanson.service.sap.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


eureka:
  instance:
    hostname: 47.114.188.60
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://106.12.184.126:8060/eureka/
