server:
  port: 8770
spring:
  application:
    name: wechat-api
  zipkin:
    base-url: http://106.12.184.126:8881
eureka:
  instance:
    hostname: 49.234.225.92
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://106.12.184.126:8060/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000

security:
  oauth2:
    client:
      client-id: miniWehcat
      client-secret: password
      user-authorization-uri: http://localhost:8890/oauth/authorize
      access-token-uri: http://localhost:8890/oauth/token #ªÒ»°Token
    resource:
      jwt:
        key-uri: http://localhost:8890/oauth/token_key
