server:
  port: 8860

spring:
  application:
    name: zuul-gateway
  boot:
    admin:
      client:
        url: http://116.62.6.120:8880
  zipkin:
    base-url: http://116.62.6.120:8881
  servlet:
    multipart:
      max-file-size: 50Mb
      max-request-size: 100Mb

eureka:
  instance:
    hostname: 116.62.6.120
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://116.62.6.120:8060/eureka/
zuul:
  routes:
    admin-feign:
      path: /api/dingtalk/**
      serviceId:  dingtalk-web
    tort-feign:
      path: /api/tort/**
      sensitiveHeaders:
      serviceId:  tort-api
    auth:
      path: /auth/**
      sensitiveHeaders:
      serviceId:  sso-oauth2
    wechat:
      path: /wx/**
      sensitiveHeaders:
      serviceId:  wechat-api
    image:
      path: /image/**
      sensitiveHeaders:
      serviceId:  wechat-service
    sap:
      path: /sap/**
      sensitiveHeaders:
      serviceId:  sap-api
    sap-service:
      path: /sapSerive/**
      sensitiveHeaders:
      serviceId:  sap-service
  add-proxy-headers: true
#设置熔断是为6秒 并取消重试
ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  OkToRetryOnAllOperations: false
  eureka:
    enabled: true
#关闭超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
